# Author: Justyna Pawlata
# Project Euler (https://projecteuler.net/)

# Problem 2:
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fibonacci_seq(limit, list_seq):
    while True:
        step = list_seq[-1] + list_seq[-2]
        if step < limit:
            list_seq.append(step)
        else:
            break
    return list_seq

limit = 4000000
list_seq = [1, 2]

numbers = fibonacci_seq(limit, list_seq)
# even numbers only
answer = sum([x for x in numbers if x % 2 == 0])
print(answer)